# _config.yml
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Roman Aliaskarov
email: r.aliaskarov@gmail.com
description: >
 Portfolio page

# hosting settings
baseurl: "/my-portfolio" # the subpath of your site, e.g. /blog
url: "https://raliaskarov.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  raliaskarov

# enable tree of content (see sidebar so see effect)
toc:
    enabled: true

# Build settings
# theme: minima
# theme below fits well for long content
remote_theme: sighingnow/jekyll-gitbook
toc:
    enabled: true

plugins:
  - jekyll-feed

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# here all content stored in folder _pages will have same settings as below
collections:
  pages:
    output: true
    permalink: /:collection/:path/

# make site to search through following folders
include:
    - _pages/
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
